blank_issues_enabled: false
pull_request_templates:
  - name: "ğŸš€ Feature PR"
    file: feature_pr.md
  - name: "ğŸ› Bug Fix PR"
    file: bug_fix_pr.md
  - name: "ğŸ“– Documentation PR"
    file: documentation_pr.md
  - name: "ğŸ”„ Dependency Update PR"
    file: dependency_update_pr.md
