blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/smorin/py-launch-blueprint/discussions
    about: Please ask and answer questions here.
  - name: Open Source Discord Community
    url: https://discord.gg/3zh8JyV6fU
    about: Join the Discord community to get help and share your projects.
